### PR TITLE
Kebab Remap, Chicken Ranch gone, 5 new buildings outside Kebab

### PR DESCRIPTION
**Pull request by John-Dang**
## Description
The town of Kebab has been completely remapped, with two farmer and one doctor role removed for balance. The chapel has been moved inside Kebab and the town has been made into a settlement you could find in one of the classic fallout games. Five additional locations have been added near Kebab that serve as both minor dungeons and local landmarks.

## Motivation and Context
Kebab is always a ghost town and players do not feel any reason to stick around, which makes it devoid of RP besides the bar. I wanted to make Kebab a place where players would try and build their homes and could engage in organic RP besides drinking. I have made Kebab into a fallout town that people will feel engaged with, and I also removed all the dildos and some of the high level secret DR mapper loot spawns that were easy to get if you knew which house walls to knock out, and I also removed some non-lore friendly outfits like Japanese schoolgirl outfits, geisha dresses, bunny performer outfits, etc.

## How Has This Been Tested?
Swigs will test it.

## Screenshots (if appropriate):
DIY Store
Dustbowl Library
Kebab 1
Kebab 2
Kebab 3
Kebab 4
Kebab Bird Eye View
Mini-Mart and Gun Store
Shady Bar

## Changelog (necessary)
:cl:
Map; Removed Chicken Ranch, Added Shady Bar, Added Mini-Mart, Added Gun Store, Added Dusty Library, Added DIY Store, Removed Kebab, Added New Kebab, removed 2 farmer roles, removed 1 doctor role.
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
image

I would change this whole part to be more square and in line with the rest of the city. It stands out like a tumor, and it isn't even used for anything relevant. There's definitely a better way to set this up.

**Comment by SwiGs1** [comment]
I'll sort it out DR code is missing all the pieces to most of walls especially composite. They d don't even have all 4 corner pieces. Will fix it ASAP, then weezer can remap :))

**Comment by SwiGs1** [comment]
https://cdn.discordapp.com/attachments/720550407985823796/735547846249414757/20200723_032423.jpg

**Comment by SwiGs1** [comment]
Looks good, watched you make the whole thing from scratch 👍

**Pull request merged**
