### PR TITLE
Adds german african uniform and craftable respirator, adjusts scavenger suit's armor values.

### PR DESCRIPTION
**Pull request by Ecologistos**
## Description

Adds german african uniform and craftable respirator, adjusts scavenger suit's armor values.

## Motivation and Context

Fella asked to add german uniform and bugged about it for several days, so I had to add it.
I love gas masks and respirators and, actually, Fallout lacks them despite the fact people literally live in a radioactive hellhole, so it's logical to have _at least_ respirators here.
## How Has This Been Tested?

Localhosted and fixed several times. Shouldn't have similar problem helmets had.
## Screenshots (if appropriate):
image
image
image
image
## Changelog (necessary)
:cl:
add: Added craftable respirator and german uniform.
balance: scavenger set and soviet armor balancing.
/:cl:

### CODE REVIEW

**Comment by Ecologistos** [comment]
Wait a moment...
Oh fuck.

**Comment by SwiGs1** [comment]
I don't see why a German African uniform from the early 1900s from like German west Africa should exist 380 years after. Piss them off and keep respirators they look cool.

**Comment by Ecologistos** [comment]
Alright.

**Comment by Ecologistos** [comment]
Done.

**Comment by Egorium** [comment]
> I don't see why a German African uniform from the early 1900s from like German west Africa should exist 380 years after. Piss them off and keep respirators they look cool.

That is, the Soviet form can exist after 300 years, but the German one for some reason cannot?

**Comment by SwiGs1** [comment]
> > I don't see why a German African uniform from the early 1900s from like German west Africa should exist 380 years after. Piss them off and keep respirators they look cool.
> 
> That is, the Soviet form can exist after 300+ years, but the German one for some reason cannot?

Hi, German African uniforms don't exist because they're no reference of them in any of the fallout lore. Soviet and Communistic Stuff does, ever so loosely. While it's more on the Chinese communist side they're considered part of the whole communist section of the lore. In the lore of fallout, Germany Never recovered from the war and Europe became a bunch of commonwealth with countries being merged, etc. Hence why German and everything in relation to Germany isn't really in lore that I can find

**Pull request merged**
